name: apm_251_pr01_samuelduartegomes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pedra.png
    - assets/papel.png
    - assets/tesoura.png
    - assets/jokenpo.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/jokenpo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/jokenpo.png
  android: true
  ios: false